export const types = {
  SET_RECTANGLE: "SET_RECTANGLE",
  GET_NORMAL_MAP: "GET_NORMAL_MAP",
  GET_NORMAL_MAP_SUCCESS: "GET_NORMAL_MAP_SUCCESS",
  GET_NORMAL_MAP_FAILED: "GET_NORMAL_MAP_FAILED",
  GET_NORMAL_MAP_LOADING: "GET_NORMAL_MAP_LOADING"
};

export const urls = {
  upload: "/upload/"
};
